### ISSUE TITLE
I am interested in using Rabbitmq managed services instead of a statefulset. How can I achieve this?

### ISSUE THREAD

**Issue by RahulKumar1119** [josephnhtam/vsp-youtube-clone-microservices#17]
@josephnhtam  I am interested in using Rabbitmq managed services instead of a stateful set. How can I achieve this?

Rabbitmq URL: amqps://example.mq.ap-south-1.amazonaws.com:5671

**Comment by josephnhtam** [comment]
You can configure RabbitMQ via environment variable like this https://github.com/josephnhtam/vsp-youtube-clone-microservices/blob/master/Deploy/kubernetes/video-manager-api/overlays/minikube/patches/secret.env
